### ISSUE TITLE
SMS converations

### ISSUE THREAD

**Issue by jtekelenburg** [monty5811/apostello#55]
https://www.twilio.com/docs/quickstart/python/sms/tracking-conversations

**Comment by monty5811** [comment]
## idea

To flesh this out some more - the idea would be to allow a back a forth conversation with a user over SMS.

This would, for example, allow you to setup a questionnaire:

 - User texts `signup`
 - apostello replies: `Hi, what's your name`
 - user replies `bob`
 - apostello replies: `Thanks, what's your email?`
 - etc

This could be implemented by tracking users in a session like https://www.twilio.com/docs/quickstart/python/sms/tracking-conversations 

## issue

I'm not sure how we can do this and guarantee a response will not clash with a keyword and potentially be very confusing for users. For example:

- We have two keywords: `signup` and `lunch`
- When a user texts `signup` we want to ask them what their favourite meal is
- The user may then reply: `lunch`

Now apostello has no way to determine where the incoming message should go. Is it an answer to the favourite meal question? Or has the user ignored the question/not received it yet and is trying to use the `lunch` keyword?

One possible way to handle this would be to disable keyword matching when a user is in a Q&A session. But I think this would complicate things for users and we would need a way to communicate how to escape the session before the session time out.

I'm not sure of a reliable way to over come this problem.

## make shift solution

A makeshift solution that is possible in apostello today is to daisy chain existing keywords so that one keyword's reply points the user to the next keyword to use. To take the example above, the `signup` keyword response would tell the user how to use the `email` keyword and the `email` keyword response would describe the next step in the chain.

## conclusion

Unless we can find a way to reliably have responses work alongside keywords, I don't think this is a viable idea for apostello.

**Comment by monty5811** [comment]
Closing.

Will re-open if there is renewed interest or anyone has a good idea on how to do this.
